# Generated by Django 4.1.6 on 2023-02-06 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('url_img', models.CharField(max_length=500)),
                ('supplier_link', models.CharField(max_length=500)),
            ],
        ),
    ]
